norm = BpBatchNorm()
baseconv = BpDoubleConv(conv1=BpConv(), conv2=BpConv())
ups = BpPixelShuffleUp()
dws = BpMaxDown()
dec = BpUDecoder(convolution=baseconv, upsampler=ups)
enc = BpUEncoder(convolution=BpDoubleConv(conv1=BpConv(stride=2), conv2=BpConv()), downsampler=nothing)
bdg = BpUBridge(convolution=baseconv, downsampler=dws, upsampler=ups)
h = BpPixelClassifier(nclasses=4)
unet = BpUNet(encoder=enc, decoder=dec, bridge=bdg, head=h, expansion=2, basewidth=16)
m = make(unet)
@test Flux.outputsize(m, (32, 32, 3, 2)) == (32, 32, 4, 2)
